name: FirstJoinPlus
version: '2.4.1'
main: com.chaseoes.firstjoinplus.FirstJoinPlus
description: FirstJoinPlus by chaseoes.
api-version: '1.21'
authors:
  - chaseoes
website: http://dev.bukkit.org/server-mods/firstjoinplus/
permissions:
  firstjoinplus.reload:
    description: Permission to use the /firstjoinplus reload command.
    default: op
  firstjoinplus.setspawn:
    description: Permission to use the /firstjoinplus setspawn command.
    default: op
  firstjoinplus.debug:
    description: Permission to use the /firstjoinplus debug command.
    default: op
  firstjoinplus.notify:
    description: Permission to hear the first-join sound notification.
    default: true
