name: FirstJoinPlus
main: com.chaseoes.firstjoinplus.FirstJoinPlus
version: 2.4.1
description: FirstJoinPlus by chaseoes.
api-version: '1.21'
author: chaseoes
website: http://dev.bukkit.org/server-mods/firstjoinplus/
softdepend: [GeoIPTools]
commands:
  firstjoinplus:
    description: FirstJoinPlus command(s).
    aliases: fjp
    usage: /firstjoinplus [reload|setspawn|debug]
permissions:
  firstjoinplus.reload:
    description: Permission to use the /firstjoinplus reload command.
  firstjoinplus.setspawn:
    description: Permission to use the /firstjoinplus setspawn command.
  firstjoinplus.debug:
    description: Permission to use the /firstjoinplus debug command.
  firstjoinplus.notify:
    description: Permission to hear the first-join sound notification.
